version: '2.1'
services:
  service-a:
    image: fox89/minimal-docker-http-server
    networks:
     - jwt
  service-b:
    image: fox89/minimal-docker-http-server
    networks:
     - jwt
  web:
    build: .
    environment:
      - JWT_SECRET=18732kybhkbfkhbdfsdfs
      - JWT_ISSUER=joel
      - FILTER_HEADER=my-header
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - service-a
     - service-b
    networks:
     - jwt
networks:
  jwt:
